language: generic
sudo: required
service:
  - dockerfile

before install:
  - docker build -t my-docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true my-docker-react npm run test

deploy: 
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-851234341428"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"